-- 코드를 작성해주세요
SELECT ID, 
CASE 
WHEN QUART = 1 THEN 'CRITICAL'
WHEN QUART = 2 THEN 'HIGH'
WHEN QUART = 3 THEN 'MEDIUM'
WHEN QUART = 4 THEN 'LOW'
END AS COLONY_NAME
FROM (
SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUART FROM ECOLI_DATA
) AS T
ORDER BY ID